# Example Prometheus configuration for docker-compose
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Example job - replace with your actual targets
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # Add your own scrape configs here
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']